# Form implementation generated from reading ui file 'createscenario.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import json
import pathlib
from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtWidgets import QFileDialog
from PySide6.QtGui import QImage
from DataTypes.Scenario import Scenario
from Database import Database

class Ui_CreateScenario(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 260, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.plainTextEdit_scenarioName = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_scenarioName.setGeometry(QtCore.QRect(10, 29, 369, 31))
        self.plainTextEdit_scenarioName.setObjectName("plainTextEdit_scenarioName")

        self.label_dimensions = QtWidgets.QLabel(parent=Dialog)
        self.label_dimensions.setGeometry(QtCore.QRect(10, 90, 161, 17))
        self.label_dimensions.setObjectName("label_dimensions")

        self.label_scenarioName = QtWidgets.QLabel(parent=Dialog)
        self.label_scenarioName.setGeometry(QtCore.QRect(10, 6, 369, 17))
        self.label_scenarioName.setObjectName("label_scenarioName")

        self.label_refImage = QtWidgets.QLabel(parent=Dialog)
        self.label_refImage.setGeometry(QtCore.QRect(10, 170, 171, 17))
        self.label_refImage.setObjectName("label_refImage")

        self.plainTextEdit_height = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_height.setGeometry(QtCore.QRect(90, 110, 61, 31))
        self.plainTextEdit_height.setObjectName("plainTextEdit_height")

        
        self.plainTextEdit_width = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_width.setGeometry(QtCore.QRect(10, 110, 61, 31))
        self.plainTextEdit_width.setObjectName("plainTextEdit_width")

        self.plainTextEdit_refImage = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_refImage.setGeometry(QtCore.QRect(10, 190, 321, 31))
        self.plainTextEdit_refImage.setObjectName("plainTextEdit_refImage")

        self.button_searchFiles = QtWidgets.QToolButton(parent=Dialog)
        self.button_searchFiles.setGeometry(QtCore.QRect(340, 190, 31, 31))
        self.button_searchFiles.setObjectName("button_searchFiles")


        self.retranslateUi(Dialog)

        #self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_dimensions.setText(_translate("Dialog", "Specify the dimensions"))
        self.label_scenarioName.setText(_translate("Dialog", "Specify the Scenario Name"))
        self.label_refImage.setText(_translate("Dialog", "Select a reference image"))
        self.button_searchFiles.setText(_translate("Dialog", "..."))


